name: Deploy Vibrant Life Med Spa to AWS

on:
  push:
    branches:
      - main  # Change to your main branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 23.2.0 

    - name: Install Dependencies
      run: npm install --legacy-peer-deps

    - name: Build React App
      env:
        CI: false  # Prevent warnings from breaking the build
      run: npm run build

    - name: Deploy to AWS Server
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}  # Add your private SSH key in GitHub Secrets
      run: |
        echo "${SSH_KEY}" > ssh_key
        chmod 600 ssh_key
        ssh -i ssh_key -o StrictHostKeyChecking=no <USER>@<SERVER> << 'EOF'
        cd /var/www/booking.vibrantlifespa.com/html/
        sudo rm -rf vibrantlifespa-web public src
        git clone https://github.com/ShizaSiddiqui/vibrantlifespa-web.git
        sudo mv vibrantlifespa-web/* .
        npm i --legacy-peer-deps
        npm run build
        EOF